/* ═══════════════════════════════════════════════════════════════════════
   NEXBOT SOLO BUSINESS DASHBOARD — INITIAL REAL DATA STORE
   Echte Datenbasis aus Businessplan, top_15_money_leads.json & Nexbot Organisation
   ═══════════════════════════════════════════════════════════════════════ */

export const INITIAL_DATA = {
  metrics: {
    revenueTarget: 5000,
    currentRevenue: 1250,
    targetMRR: 156,
    currentMRR: 39,
    targetDealsCount: 4,
    closedDealsCount: 1,
    pipelineValue: 13750,
    demosGenerated: 21,
    demosSent: 9,
    openInvoicesAmount: 0
  },

  top3Hebel: [
    {
      id: "hebel-1",
      rank: 1,
      text: "Saridis SHK & Fünfer Werner Spenglerei anrufen (Saxer Opener & Erlaubnis für WhatsApp Demo-Link)",
      category: "Akquise",
      isDone: false,
      leadId: "lead-001"
    },
    {
      id: "hebel-2",
      rank: 2,
      text: "Loom-Video für Faschingbauer Haustechnik aufnehmen (60s Smartphone Tour mit Branchenrechner)",
      category: "Akquise",
      isDone: false,
      leadId: "lead-009"
    },
    {
      id: "hebel-3",
      rank: 3,
      text: "BGB-Projektvertrag & AVV für nächste Verhandlung aus 'Nexbot Organisation' prüfen",
      category: "Recht/SLA",
      isDone: true,
      docId: "doc-002"
    }
  ],

  leads: [
    {
      id: "lead-001",
      companyName: "Saridis SHK",
      ownerName: "Herr Saridis",
      category: "Sanitär & Heizung",
      city: "Ingolstadt",
      street: "Geibelstraße 22",
      phone: "+49 1523 7384702",
      googleRating: 5.0,
      reviewCount: 12,
      topReviewQuote: "Schnellster Notdienst und saubere Arbeit beim Heizungstausch.",
      status: "pitch_versendet",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://saridis-shk.vercel.app",
      localDemoPath: "../saridis-shk/index.html",
      loomUrl: "https://loom.com/share/saridis-shk-demo-tour",
      contractFile: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Sehr freundlich am Telefon. Chef ist abends ab 18:00 Uhr via WhatsApp erreichbar. Fokus: Badsanierung & Heizungs-Rechner.",
      createdAt: "2026-09-10",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-002",
      companyName: "Fünfer Werner Spenglerei Meisterbetrieb",
      ownerName: "Werner Fünfer",
      category: "Dachdecker & Spenglerei",
      city: "Ingolstadt",
      street: "Einbogen 2",
      phone: "+49 841 9711378",
      googleRating: 5.0,
      reviewCount: 7,
      topReviewQuote: "Zuverlässiger Spenglermeister. Schnelle Reparatur am Dach nach Sturm.",
      status: "verhandlung",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://bauspenglerei-pospisil.vercel.app",
      localDemoPath: "../bauspenglerei-pospisil/index.html",
      loomUrl: "https://loom.com/share/fuenfer-spenglerei-pitch",
      contractFile: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Haben aktuell keine Website. War positiv überrascht, dass Entwurf bereits steht. BGB-Vertrag vorbereitet.",
      createdAt: "2026-09-11",
      lastContactAt: "2026-09-16"
    },
    {
      id: "lead-003",
      companyName: "Bauspenglerei Pospisil",
      ownerName: "Herr Pospisil",
      category: "Bauspenglerei",
      city: "Ingolstadt",
      street: "Münchener Str. 14",
      phone: "+49 841 931200",
      googleRating: 4.9,
      reviewCount: 18,
      topReviewQuote: "Präzise Spenglerarbeiten und faire Festpreise.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://bauspenglerei-pospisil.vercel.app",
      localDemoPath: "../bauspenglerei-pospisil/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Demo ist live auf Vercel Edge. Loom-Tour für WhatsApp vorbereiten.",
      createdAt: "2026-09-12",
      lastContactAt: "2026-09-14"
    },
    {
      id: "lead-004",
      companyName: "Bauhandwerk Stey",
      ownerName: "Markus Stey",
      category: "Bauunternehmen & Sanierung",
      city: "Ingolstadt",
      street: "Gaimersheimer Str. 45",
      phone: "+49 841 493012",
      googleRating: 4.8,
      reviewCount: 22,
      topReviewQuote: "Solides Handwerk, termingerechte Fertigstellung der Sanierung.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://bauhandwerk-stey.vercel.app",
      localDemoPath: "../bauhandwerk-stey/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Demo mit m²-Kostenrechner fertig. Kontaktversuch morgen früh.",
      createdAt: "2026-09-13",
      lastContactAt: "2026-09-14"
    },
    {
      id: "lead-005",
      companyName: "Robert Protzmann",
      ownerName: "Robert Protzmann",
      category: "Dachdecker",
      city: "Augsburg",
      street: "Zur Inninger Mühle 4",
      phone: "+49 821 995407",
      googleRating: 4.5,
      reviewCount: 26,
      topReviewQuote: "Sehr gute Dachneueindeckung, eingespieltes Team.",
      status: "recherchiert",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "",
      localDemoPath: "",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Etablierter Dachdecker mit 26 Rezensionen. Braucht moderne mobile Präsenz für 15k€ Sanierungsanfragen.",
      createdAt: "2026-09-14",
      lastContactAt: "2026-09-14"
    },
    {
      id: "lead-006",
      companyName: "Baugeschäft Sipala Antonino Meisterbetrieb",
      ownerName: "Antonino Sipala",
      category: "Bauunternehmen",
      city: "Augsburg Umgebung",
      street: "Siedlerweg 92",
      phone: "+49 821 74799460",
      googleRating: 4.8,
      reviewCount: 11,
      topReviewQuote: "Exzellente Rohbauarbeiten, saubere Baustelle.",
      status: "demo_in_produktion",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "",
      localDemoPath: "",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Website-Generator v3.2 baut gerade die Demo.",
      createdAt: "2026-09-15",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-007",
      companyName: "Samir Zogaj - Bodenbeläge",
      ownerName: "Samir Zogaj",
      category: "Bodenleger & Parkett",
      city: "Ingolstadt",
      street: "Hainbuchenstraße 8",
      phone: "+49 1523 7901695",
      googleRating: 5.0,
      reviewCount: 13,
      topReviewQuote: "Perfekt verlegtes Parkett, termintreu und sauber.",
      status: "recherchiert",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "",
      localDemoPath: "",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "13 Top-Bewertungen, aber keine Website. Hoher Vorher-Nachher Bilder-Bedarf.",
      createdAt: "2026-09-15",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-008",
      companyName: "DKS Hausmeisterservice & GalaBau",
      ownerName: "Herr DKS",
      category: "Garten- & Landschaftsbau",
      city: "Regensburg",
      street: "Dr.-Gessler-Straße 12a",
      phone: "+49 176 43671680",
      googleRating: 5.0,
      reviewCount: 11,
      topReviewQuote: "Gartenumgestaltung und Pflasterung auf höchstem Niveau.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://gaertnerei-josef-brunner.vercel.app",
      localDemoPath: "../gaertnerei-josef-brunner/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Regensburg B2B Markt. Dauerverträge für Objektbetreuung & Privatgärten.",
      createdAt: "2026-09-13",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-009",
      companyName: "Faschingbauer Haustechnik",
      ownerName: "Josef Faschingbauer",
      category: "Sanitär & Estrich",
      city: "Ingolstadt",
      street: "Eichenwaldstraße 55",
      phone: "+49 171 8914790",
      googleRating: 4.4,
      reviewCount: 5,
      topReviewQuote: "Gute Beratung beim Heizungstausch.",
      status: "verhandlung",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://faschingbauer-haustechnik.vercel.app",
      localDemoPath: "../faschingbauer-haustechnik/index.html",
      loomUrl: "",
      contractFile: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Hatte Bedenken wegen Zeitaufwand ('Baustelle voll'). Bumerang-Einwand erfolgreich: 'Arbeit ist schon getan!'",
      createdAt: "2026-09-12",
      lastContactAt: "2026-09-16"
    },
    {
      id: "lead-010",
      companyName: "Heizung Mantsch",
      ownerName: "Herr Mantsch",
      category: "Heizungs- & Klimatechnik",
      city: "Ingolstadt",
      street: "Kurt-Huber-Straße 19",
      phone: "+49 8458 3465357",
      googleRating: 4.2,
      reviewCount: 10,
      topReviewQuote: "Schnelle Hilfe als die Heizung im Winter ausfiel.",
      status: "pitch_versendet",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://heizung-mantsch.vercel.app",
      localDemoPath: "../heizung-mantsch/index.html",
      loomUrl: "https://loom.com/share/heizung-mantsch-tour",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Alte HTTP-Website aus 2008 ersetzt durch Highspeed-Vercel-Edge Auftritt.",
      createdAt: "2026-09-10",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-011",
      companyName: "MHG Heiztechnik",
      ownerName: "Herr MHG",
      category: "Sanitär & Heizung",
      city: "Ingolstadt",
      street: "Münchener Str. 205",
      phone: "+49 841 8869755",
      googleRating: 5.0,
      reviewCount: 3,
      topReviewQuote: "Sehr freundlicher Kundendienst.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://mhg-heiztechnik.vercel.app",
      localDemoPath: "../mhg-heiztechnik/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Demo steht. Kaltakquise-Anruf geplant.",
      createdAt: "2026-09-14",
      lastContactAt: "2026-09-14"
    },
    {
      id: "lead-012",
      companyName: "Ulrich Pokorny Sanitärtechnik",
      ownerName: "Ulrich Pokorny",
      category: "Sanitärtechnik",
      city: "Ingolstadt",
      street: "Tulpenstraße 6",
      phone: "+49 841 71918",
      googleRating: 5.0,
      reviewCount: 2,
      topReviewQuote: "Zuverlässiger Meister, prompte Abwicklung.",
      status: "pitch_versendet",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://ulrich-pokorny-sanitaertechnik.vercel.app",
      localDemoPath: "../ulrich-pokorny-sanitaertechnik/index.html",
      loomUrl: "https://loom.com/share/pokorny-sanitaer",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "WhatsApp Micro-Commitment erhalten. Follow-Up Call am Donnerstag 10:00 Uhr.",
      createdAt: "2026-09-11",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-013",
      companyName: "Weidlich Malermeister",
      ownerName: "Klaus Weidlich",
      category: "Maler & Lackierer",
      city: "Augsburg",
      street: "Ulmer Str. 78",
      phone: "+49 821 441020",
      googleRating: 4.9,
      reviewCount: 15,
      topReviewQuote: "Fassadenanstrich sieht fantastisch aus. Pünktlich und sauber.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://weidlich-malermeister.vercel.app",
      localDemoPath: "../weidlich-malermeister/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Demo mit Farbfächer-Interaktion fertiggestellt.",
      createdAt: "2026-09-14",
      lastContactAt: "2026-09-15"
    },
    {
      id: "lead-014",
      companyName: "Wilhelm Lippl Handwerk",
      ownerName: "Wilhelm Lippl",
      category: "Allround-Handwerk & Montage",
      city: "Ingolstadt",
      street: "Regensburger Str. 210",
      phone: "+49 841 36681",
      googleRating: 5.0,
      reviewCount: 3,
      topReviewQuote: "Echtes bayerisches Handwerk, ehrlich und schnell.",
      status: "demo_live",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://wilhelm-lippl-handwerk.vercel.app",
      localDemoPath: "../wilhelm-lippl-handwerk/index.html",
      loomUrl: "",
      contractFile: "",
      invoiceStatus: "noch_nicht_faellig",
      notes: "Übungs-Lead. Fokus: Schneller Einstieg ohne Nervosität.",
      createdAt: "2026-09-13",
      lastContactAt: "2026-09-14"
    },
    {
      id: "lead-015",
      companyName: "Musterkunde Bayern GmbH",
      ownerName: "Max Mustermann",
      category: "B2B Mittelstand / Handwerk",
      city: "Ingolstadt",
      street: "Musterstraße 12",
      phone: "+49 841 998877",
      googleRating: 5.0,
      reviewCount: 20,
      topReviewQuote: "Ausgezeichnete Zusammenarbeit mit Nexbot Webdesign. Ladezeit unter 1s!",
      status: "gewonnen",
      dealValue: 1250,
      monthlyRetainer: 39,
      demoUrl: "https://musterkunde.nexbot.info",
      localDemoPath: "../../Nexbot Organisation/INDEX_NEXBOT_ORGANISATION.html",
      loomUrl: "https://loom.com/share/musterkunde-showcase",
      contractFile: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      invoiceStatus: "bezahlt",
      notes: "Erster erfolgreicher Abschluss nach Businessplan! 1.250 € erhalten, monatlicher Retainer 39 € per SEPA aktiv.",
      createdAt: "2026-03-01",
      lastContactAt: "2026-09-01"
    }
  ],

  clients: [
    {
      id: "client-001",
      leadId: "lead-015",
      companyName: "Musterkunde Bayern GmbH",
      contactPerson: "Max Mustermann (Geschäftsführer)",
      domain: "musterkunde-bayern.de",
      startDate: "2026-03-01",
      contractType: "Modern UI Pro Webdesign + Care Retainer",
      oneTimePrice: 1250,
      monthlyRetainer: 39,
      paymentMethod: "SEPA-Lastschrift",
      status: "aktiv",
      supportBudgetMinutes: 30,
      usedMinutesThisMonth: 10,
      contractFile: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      avvFile: "../../Nexbot Organisation/02_Verträge/02_AVV_Datenschutz_DSGVO.html",
      acceptanceFile: "../../Nexbot Organisation/02_Verträge/03_Abnahmeprotokoll_Webdesign_BGB.html",
      latestInvoiceNumber: "RE-2026-001",
      invoiceStatus: "bezahlt"
    }
  ],

  documents: [
    {
      id: "doc-001",
      title: "Nexbot Musterangebot Webdesign",
      category: "01_Angebote",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "1.250 € + 39 €/Mtl.",
      status: "angenommen",
      date: "2026-02-20",
      filePath: "../../Nexbot Organisation/01_Angebote/Nexbot_Musterangebot_Webdesign.html",
      description: "Verbindliches Festpreisangebot mit 0 € Vorab-Risiko Klausel nach Businessplan."
    },
    {
      id: "doc-002",
      title: "01 Webdesign Projektvertrag BGB",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "1.250 €",
      status: "unterzeichnet",
      date: "2026-02-28",
      filePath: "../../Nexbot Organisation/02_Verträge/01_Webdesign_Projektvertrag_BGB.html",
      description: "Werkvertrag nach §§ 631 ff. BGB mit digitaler Signatur & Urheberrechtsklausel."
    },
    {
      id: "doc-003",
      title: "02 AVV Auftragsverarbeitung (Art. 28 DSGVO)",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "Inklusive",
      status: "unterzeichnet",
      date: "2026-02-28",
      filePath: "../../Nexbot Organisation/02_Verträge/02_AVV_Datenschutz_DSGVO.html",
      description: "Rechtssicherer Datenschutz-Vertrag gem. Art. 28 DSGVO inklusive Bitkom TOM Anlage."
    },
    {
      id: "doc-004",
      title: "03 Abnahmeprotokoll Webdesign (§ 640 BGB)",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "Fälligkeit ausgelöst",
      status: "abgenommen",
      date: "2026-03-05",
      filePath: "../../Nexbot Organisation/02_Verträge/03_Abnahmeprotokoll_Webdesign_BGB.html",
      description: "Rechtsverbindliche Abnahme nach § 640 BGB – löst Werklohnfälligkeit aus."
    },
    {
      id: "doc-004a",
      title: "04 Standard Agentur-AGB (B2B)",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "Rechtsstandard",
      status: "vorhanden",
      date: "2026-03-05",
      filePath: "../../Nexbot Organisation/02_Verträge/04_Agentur_AGB_BGB.html",
      description: "Rechtssichere B2B-AGB gem. §§ 305 ff. BGB mit Verzugszinsen, Urheberrechtsklausel & Abnahmefiktion."
    },
    {
      id: "doc-004b",
      title: "05 Wartungs- & Servicevertrag (SLA)",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "49,00 € / Mt.",
      status: "aktiv",
      date: "2026-03-05",
      filePath: "../../Nexbot Organisation/02_Verträge/05_Wartungs_und_Servicevertrag.html",
      description: "Dienstvertrag nach §§ 611 ff. BGB über Highspeed-Hosting, wöchentliche Backups, 24h SLA und integriertes SEPA-Lastschriftmandat."
    },
    {
      id: "doc-004c",
      title: "06 Kunden-Anpassungsfragebogen",
      category: "02_Verträge",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "Workflow",
      status: "aktiv",
      date: "2026-03-05",
      filePath: "../../Nexbot Organisation/02_Verträge/06_Kunden_Anpassungsfragebogen.html",
      description: "Standardisierter Korrekturbogen für Feedbackschleife 1 von 2 (Texte, Farben, Bilder, Struktur) gem. § 4 Abs. 3 Werkvertrag."
    },
    {
      id: "doc-005",
      title: "Kleinunternehmer-Rechnung RE-2026-001",
      category: "03_Rechnungen",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "1.250,00 €",
      status: "bezahlt",
      date: "2026-03-05",
      dueDate: "2026-03-19",
      filePath: "../../Nexbot Organisation/03_Rechnungen/Nexbot_Kleinunternehmer_Rechnung.html",
      description: "Rechnung nach §§ 14, 14a UStG i.V.m. § 19 UStG (14 Tage Zahlungsziel)."
    },
    {
      id: "doc-006",
      title: "Retainer-Rechnung RE-2026-002 (März)",
      category: "03_Rechnungen",
      clientName: "Musterkunde Bayern GmbH",
      leadId: "lead-015",
      amount: "39,00 €",
      status: "bezahlt",
      date: "2026-03-15",
      dueDate: "2026-03-29",
      filePath: "../../Nexbot Organisation/03_Rechnungen/Nexbot_Kleinunternehmer_Rechnung.html",
      description: "Monatlicher Retainer für Vercel Edge Hosting, SSL & Wartungsservice."
    },
    {
      id: "doc-007",
      title: "EÜR Rechner 2026 Web-App",
      category: "04_Buchhaltung_EÜR",
      clientName: "Nexbot Webdesign (Eigenbeleg)",
      leadId: null,
      amount: "Übersicht",
      status: "aktiv",
      date: "2026-09-15",
      filePath: "../../Nexbot Organisation/04_Buchhaltung_EÜR/Nexbot_EUER_Rechner_2026.html",
      description: "Interaktiver EÜR-Rechner mit Grenzwert-Radar für 25.000 € Kleinunternehmer-Reform."
    },
    {
      id: "doc-008",
      title: "Gewerbeanmeldung Manching (GewA1)",
      category: "05_Behörden_Unterlagen",
      clientName: "Gemeinde Manching / Finanzamt",
      leadId: null,
      amount: "Amtlich",
      status: "bestätigt",
      date: "2026-09-15",
      filePath: "../../Nexbot Organisation/05_Behörden_Unterlagen/Gewerbemeldung.pdf",
      description: "Offizielle Gewerbeanmeldung für Nexbot Webdesign & Softwareentwicklung."
    },
    {
      id: "doc-009",
      title: "ELSTER USt-IdNr. & Steuerunterlagen",
      category: "05_Behörden_Unterlagen",
      clientName: "Finanzamt Pfaffenhofen / BZSt",
      leadId: null,
      amount: "Amtlich",
      status: "bestätigt",
      date: "2026-09-15",
      filePath: "../../Nexbot Organisation/05_Behörden_Unterlagen/ELSTER-USt-IdNr.pdf",
      description: "Umsatzsteuer-Identifikationsnummer & Fragebogen zur steuerlichen Erfassung."
    },
    {
      id: "doc-010",
      title: "DNS & Vercel Domain-Leitfaden",
      category: "05_Behörden_Unterlagen",
      clientName: "Nexbot Webdesign (SOP)",
      leadId: null,
      amount: "SOP",
      status: "aktiv",
      date: "2026-03-05",
      filePath: "../../Nexbot Organisation/05_Behörden_Unterlagen/Nexbot_DNS_und_Domain_Leitfaden.html",
      description: "Technischer Leitfaden für A-Record (76.76.21.21), CNAME und schützende DNS-Konfiguration ohne Mail-Kollision."
    }
  ],

  tasks: [
    {
      id: "task-001",
      title: "5 Kaltakquise-Pitches via Saxer-Leitfaden führen",
      description: "Fokus: Saridis SHK, Fünfer Werner Spenglerei, Faschingbauer Haustechnik. Ziel: Micro-Commitment für WhatsApp Demo-Link.",
      category: "Akquise",
      priority: "P0",
      status: "offen",
      dueDate: "Heute",
      leadId: "lead-001"
    },
    {
      id: "task-002",
      title: "Loom-Video für Faschingbauer Haustechnik aufnehmen",
      description: "Smartphone-Ansicht (375px), 60-90 Sekunden. Wärmepumpen-Rechner und Rezensionen zeigen.",
      category: "Akquise",
      priority: "P0",
      status: "in_arbeit",
      dueDate: "Heute",
      leadId: "lead-009"
    },
    {
      id: "task-003",
      title: "Demo Robert Protzmann (Augsburg Dachdecker) fertigstellen",
      description: "Lead aus top_15. Dach-Rechner und Google-Rezensionen einbauen.",
      category: "Technik",
      priority: "P1",
      status: "offen",
      dueDate: "Morgen",
      leadId: "lead-005"
    },
    {
      id: "task-004",
      title: "DNS & Domain-Aufschaltung für Stey Bauhandwerk vorbereiten",
      description: "Vercel CNAME Records und SSL-Zertifikat prüfen.",
      category: "Technik",
      priority: "P1",
      status: "offen",
      dueDate: "18.09.2026",
      leadId: "lead-004"
    },
    {
      id: "task-005",
      title: "EÜR-Buchhaltung Q1-Q3 2026 Belege archivieren",
      description: "Belege Hetzner, Vercel Pro, Telekom mit Nexbot_EUER_Buchhaltung_2026.csv abgleichen.",
      category: "Verwaltung",
      priority: "P2",
      status: "erledigt",
      dueDate: "15.09.2026",
      leadId: null
    }
  ],

  coldCallScript: {
    gatekeeper: {
      title: "Phase A: Gatekeeper-Überwindung (Sekretariat / Büro)",
      speaker: "Raphael",
      dialogue: "Guten Tag, Raphael Neumeier hier. Es geht um die digitale Außendarstellung der Firma und die Gewinnung junger Fachkräfte in der Region. Bitte geben Sie mich kurz zu Herrn [Nachname Chef] durch.",
      responseExample: "Rezeption: 'Worum geht es da genau?'",
      counter: "Raphael: 'Genau darum: Ich habe hierzu bereits ein fertiges, interaktives Konzept spezifisch für Ihren Betrieb programmiert und stimme mit ihm nur kurz ab, wohin ich ihm den Direktlink senden darf. Bitte klemmen Sie mich kurz an.'"
    },
    opener: {
      title: "Phase B: Inhaber-Opener (Lob & Micro-Commitment)",
      speaker: "Raphael",
      dialogue: "Guten Tag Herr [Nachname Chef], Raphael Neumeier hier aus Ingolstadt. Herr [Nachname Chef], ich rufe Sie an, weil mir Ihre exzellenten 5,0 Sterne auf Google aufgefallen sind. Mir fällt bei Handwerksbetrieben in Ihrer Größenordnung oft auf, dass diese Qualität online überhaupt nicht sichtbar ist – und Sie dadurch lukrative Privatkunden oder junge Gesellen an Konkurrenten verlieren. Wie zufrieden sind Sie aktuell damit, wie Ihr Betrieb im Netz wahrgenommen wird?",
      pauseNotice: "(Pausieren. Kunde antworten lassen).",
      hook: "Genau aus diesem Grund habe ich auf eigenes Risiko bereits einen fertigen, interaktiven Entwurf für Sie programmiert, der Ihre 5-Sterne-Arbeit perfekt aufs Smartphone bringt. Ich möchte Ihnen das gar nicht am Telefon erklären – Sie müssen das auf Ihrem Handy sehen. Senden wir den Link am besten auf die Nummer, unter der wir gerade sprechen, oder haben Sie dafür ein Geschäftshandy mit WhatsApp?"
    },
    loomStructure: [
      { step: "0–15 Sek", title: "Gesicht & Entwurf", desc: "Gesicht zeigen, lockere persönliche Ansprache, fertigen Entwurf auf Desktop zeigen." },
      { step: "15–45 Sek", title: "Conversion-Feature", desc: "Live-Klick auf den interaktiven Rechner, die Google-Bewertungen und den WhatsApp-Button." },
      { step: "45–65 Sek", title: "Mobile DevTools", desc: "DevTools 375px: 'So sieht das aus, wenn ein Kunde abends auf der Couch nach Ihnen sucht.'" },
      { step: "65–90 Sek", title: "Call to Action", desc: "Klares Angebot: 'Wenn es Ihnen gefällt, schalten wir Ihre Domain in 24h auf. Ich rufe Sie am [Tag] kurz an.'" }
    ],
    bumerang: [
      {
        objection: "„Wir haben schon eine Agentur / macht mein Neffe“",
        reply: "„Hervorragend! Betriebe, die online schon betreut werden, nutzen meinen Entwurf extrem gerne als kostenlose Zweitmeinung, um zu prüfen, ob die aktuelle Agentur wirklich das Maximum herausholt. Schauen Sie es sich einfach unverbindlich als Benchmark an.“"
      },
      {
        objection: "„Wir haben keine Zeit / sind auf der Baustelle voll“",
        reply: "„Dass Sie auf der Baustelle voll eingespannt sind, verstehe ich völlig. Genau deshalb habe ich die Arbeit ja bereits im Vorfeld komplett erledigt, statt Ihre Zeit mit Terminen zu stehlen. Tippen Sie einfach heute Abend auf der Couch auf den Link.“"
      },
      {
        objection: "„Wir brauchen keine neuen Aufträge, wir suchen Leute“",
        reply: "„Genau deshalb ist die Seite so aufgebaut. Junge Azubis und Gesellen bewerben sich heute nicht per Postmappe – sie googeln Ihren Betrieb auf dem Smartphone. Wenn die Seite top aussieht und ein 1-Klick-Bewerbungsformular hat, gewinnen Sie die besten Leute der Region.“"
      },
      {
        objection: "„Was soll das Ganze kosten?“",
        reply: "„Genau 1.250 € einmaliger Festpreis – und Sie gehen null Vorab-Risiko ein, weil die Website ja bereits fix und fertig für Sie programmiert ist. Ein einziger neuer Handwerksauftrag refinanziert das sofort.“"
      }
    ]
  },

  callLogs: [
    {
      id: "call-001",
      date: "2026-09-15 11:30",
      companyName: "Saridis SHK",
      contactName: "Herr Saridis",
      status: "WhatsApp-Zustimmung",
      notes: "Chef erreicht. War anfangs skeptisch, aber von den Google-Rezensionen angetan. Link per WhatsApp versendet."
    },
    {
      id: "call-002",
      date: "2026-09-15 14:15",
      companyName: "Faschingbauer Haustechnik",
      contactName: "Josef Faschingbauer",
      status: "Follow-Up vereinbart",
      notes: "Sekretärin hat durchgestellt. Baustelle war laut, bat um Anruf morgen nach 17 Uhr."
    }
  ]
};
